import { DataSource } from 'typeorm';
import { Vehicle } from '../../modules/vehicles/entities/vehicle.entity';
import { Building } from '../../modules/building/entities/building.entity';
import { User } from '../../modules/users/entities/user.entity';
import { ensureUniqueSlug } from '../../common/helpers/slug.helper';

/**
 * Vehicles Seeding
 * Creates sample vehicles (cars and motorbikes) for buildings
 */
export async function seedVehicles(
  dataSource: DataSource,
  buildings: Building[],
  host?: User,
) {
  console.log('🚗 Seeding vehicles...');

  const vehicleRepository = dataSource.getRepository(Vehicle);
  const buildingRepository = dataSource.getRepository(Building);

  // Get buildings if not provided
  let buildingList = buildings;
  if (!buildingList || buildingList.length === 0) {
    buildingList = await buildingRepository.find({ take: 5 });
  }

  if (buildingList.length === 0) {
    console.log('⚠️  No buildings found, skipping vehicles...');
    return [];
  }

  const vehiclesData = [
    // Cars - For rent
    {
      type: 'oto',
      model: 'Toyota Vios',
      color: 'Trắng',
      plateNumber: '30A-12345',
      ownerName: 'Nguyễn Văn An',
      ticketNumber: 'T001',
      buildingId: buildingList[0]?.id,
      apartmentId: null,
      customerId: null,
      photo: null,
      rentalType: 'tu_lai',
      hasDriver: false,
      pricePerDay: '800000',
      pricePerHour: '100000',
      status: 'available',
      description:
        'Xe Toyota Vios 2022, màu trắng, đầy đủ tiện ích. Phù hợp cho gia đình, đi du lịch.',
      features: ['GPS', 'Bluetooth', 'Camera lùi', 'Điều hòa'],
      seats: 5,
      fuelType: 'xang',
      transmission: 'tu_dong',
      year: 2022,
      createdBy: host?.id || null,
    },
    {
      type: 'oto',
      model: 'Honda City',
      color: 'Đen',
      plateNumber: '29B-67890',
      ownerName: 'Trần Thị Bình',
      ticketNumber: 'T002',
      buildingId: buildingList[0]?.id,
      apartmentId: null,
      customerId: null,
      photo: null,
      rentalType: 'co_lai',
      hasDriver: true,
      pricePerDay: '1200000',
      pricePerHour: '150000',
      status: 'available',
      description:
        'Xe Honda City 2023, có tài xế chuyên nghiệp. Phù hợp cho công tác, đưa đón sân bay.',
      features: ['GPS', 'Bluetooth', 'Camera lùi', 'Điều hòa', 'Có tài xế'],
      seats: 5,
      fuelType: 'xang',
      transmission: 'tu_dong',
      year: 2023,
      createdBy: host?.id || null,
    },
    {
      type: 'oto',
      model: 'Mazda 3',
      color: 'Xám',
      plateNumber: '30A-11111',
      ownerName: 'Lê Văn Cường',
      ticketNumber: 'T003',
      buildingId: buildingList[1]?.id,
      apartmentId: null,
      customerId: null,
      photo: null,
      rentalType: 'tu_lai',
      hasDriver: false,
      pricePerDay: '1000000',
      pricePerHour: '120000',
      status: 'available',
      description:
        'Xe Mazda 3 2021, màu xám, sang trọng. Phù hợp cho các dịp đặc biệt.',
      features: [
        'GPS',
        'Bluetooth',
        'Camera 360',
        'Điều hòa tự động',
        'Cảnh báo va chạm',
      ],
      seats: 5,
      fuelType: 'xang',
      transmission: 'tu_dong',
      year: 2021,
      createdBy: host?.id || null,
    },
    {
      type: 'oto',
      model: 'Hyundai Accent',
      color: 'Bạc',
      plateNumber: '29B-22222',
      ownerName: 'Phạm Thị Dung',
      ticketNumber: 'T004',
      buildingId: buildingList[1]?.id,
      apartmentId: null,
      customerId: null,
      photo: null,
      rentalType: 'tu_lai',
      hasDriver: false,
      pricePerDay: '700000',
      pricePerHour: '90000',
      status: 'rented',
      description: 'Xe Hyundai Accent 2020, tiết kiệm nhiên liệu, giá rẻ.',
      features: ['GPS', 'Bluetooth', 'Điều hòa'],
      seats: 5,
      fuelType: 'xang',
      transmission: 'so_tay',
      year: 2020,
      createdBy: host?.id || null,
    },
    {
      type: 'oto',
      model: 'Ford Ranger',
      color: 'Xanh dương',
      plateNumber: '30A-33333',
      ownerName: 'Hoàng Văn Em',
      ticketNumber: 'T005',
      buildingId: buildingList[2]?.id,
      apartmentId: null,
      customerId: null,
      photo: null,
      rentalType: 'tu_lai',
      hasDriver: false,
      pricePerDay: '1500000',
      pricePerHour: '200000',
      status: 'available',
      description:
        'Xe bán tải Ford Ranger 2022, phù hợp cho công việc, đi phượt.',
      features: ['GPS', 'Bluetooth', 'Camera lùi', '4WD', 'Gầm cao'],
      seats: 5,
      fuelType: 'diesel',
      transmission: 'tu_dong',
      year: 2022,
      createdBy: host?.id || null,
    },
    // Motorbikes - For rent
    {
      type: 'xe_may',
      model: 'Honda Wave Alpha',
      color: 'Đỏ',
      plateNumber: '29B1-12345',
      ownerName: 'Nguyễn Thị Phương',
      ticketNumber: 'XM001',
      buildingId: buildingList[0]?.id,
      apartmentId: null,
      customerId: null,
      photo: null,
      rentalType: 'tu_lai',
      hasDriver: false,
      pricePerDay: '150000',
      pricePerHour: '25000',
      status: 'available',
      description:
        'Xe máy Honda Wave Alpha, tiết kiệm xăng, phù hợp đi lại trong thành phố.',
      features: ['Tiết kiệm xăng', 'Dễ điều khiển'],
      seats: 2,
      fuelType: 'xang',
      transmission: 'so_tay',
      year: 2021,
      createdBy: host?.id || null,
    },
    {
      type: 'xe_may',
      model: 'Yamaha Exciter',
      color: 'Xanh lá',
      plateNumber: '30A1-67890',
      ownerName: 'Trần Văn Giang',
      ticketNumber: 'XM002',
      buildingId: buildingList[0]?.id,
      apartmentId: null,
      customerId: null,
      photo: null,
      rentalType: 'tu_lai',
      hasDriver: false,
      pricePerDay: '200000',
      pricePerHour: '30000',
      status: 'available',
      description: 'Xe máy Yamaha Exciter 2023, mạnh mẽ, phù hợp cho giới trẻ.',
      features: ['Mạnh mẽ', 'Thiết kế thể thao'],
      seats: 2,
      fuelType: 'xang',
      transmission: 'so_tay',
      year: 2023,
      createdBy: host?.id || null,
    },
    {
      type: 'xe_may',
      model: 'Honda Vision',
      color: 'Trắng',
      plateNumber: '29B1-11111',
      ownerName: 'Lê Thị Hoa',
      ticketNumber: 'XM003',
      buildingId: buildingList[1]?.id,
      apartmentId: null,
      customerId: null,
      photo: null,
      rentalType: 'tu_lai',
      hasDriver: false,
      pricePerDay: '180000',
      pricePerHour: '28000',
      status: 'available',
      description: 'Xe máy Honda Vision, tiết kiệm xăng, dễ điều khiển.',
      features: ['Tiết kiệm xăng', 'Dễ điều khiển'],
      seats: 2,
      fuelType: 'xang',
      transmission: 'tu_dong',
      year: 2022,
      createdBy: host?.id || null,
    },
    {
      type: 'xe_may',
      model: 'SYM Attila',
      color: 'Vàng',
      plateNumber: '30A1-22222',
      ownerName: 'Phạm Văn Khoa',
      ticketNumber: 'XM004',
      buildingId: buildingList[1]?.id,
      apartmentId: null,
      customerId: null,
      photo: null,
      rentalType: null,
      hasDriver: false,
      pricePerDay: null,
      pricePerHour: null,
      status: 'unavailable',
      description: null,
      features: null,
      seats: 2,
      fuelType: 'xang',
      transmission: 'tu_dong',
      year: 2020,
      createdBy: host?.id || null,
    },
    {
      type: 'xe_may',
      model: 'Piaggio Vespa',
      color: 'Hồng',
      plateNumber: '29B1-33333',
      ownerName: 'Hoàng Thị Lan',
      ticketNumber: 'XM005',
      buildingId: buildingList[2]?.id,
      apartmentId: null,
      customerId: null,
      photo: null,
      rentalType: 'tu_lai',
      hasDriver: false,
      pricePerDay: '250000',
      pricePerHour: '40000',
      status: 'available',
      description: 'Xe tay ga Piaggio Vespa, sang trọng, phù hợp phái đẹp.',
      features: ['Sang trọng', 'Thiết kế đẹp'],
      seats: 2,
      fuelType: 'xang',
      transmission: 'tu_dong',
      year: 2022,
      createdBy: host?.id || null,
    },
    {
      type: 'xe_may',
      model: 'Honda SH',
      color: 'Đen',
      plateNumber: '30A1-44444',
      ownerName: 'Nguyễn Văn Minh',
      ticketNumber: 'XM006',
      buildingId: buildingList[2]?.id,
      apartmentId: null,
      customerId: null,
      photo: null,
      rentalType: 'tu_lai',
      hasDriver: false,
      pricePerDay: '300000',
      pricePerHour: '50000',
      status: 'available',
      description: 'Xe máy Honda SH 2023, cao cấp, đầy đủ tiện ích.',
      features: ['Cao cấp', 'Đầy đủ tiện ích', 'Khởi động bằng nút'],
      seats: 2,
      fuelType: 'xang',
      transmission: 'tu_dong',
      year: 2023,
      createdBy: host?.id || null,
    },
    {
      type: 'xe_may',
      model: 'Yamaha Grande',
      color: 'Xám',
      plateNumber: '29B1-55555',
      ownerName: 'Trần Thị Nga',
      ticketNumber: 'XM007',
      buildingId: buildingList[3]?.id,
      apartmentId: null,
      customerId: null,
      photo: null,
      rentalType: null,
      hasDriver: false,
      pricePerDay: null,
      pricePerHour: null,
      status: 'maintenance',
      description: null,
      features: null,
      seats: 2,
      fuelType: 'xang',
      transmission: 'tu_dong',
      year: 2021,
      createdBy: host?.id || null,
    },
    {
      type: 'xe_may',
      model: 'Honda Lead',
      color: 'Bạc',
      plateNumber: '30A1-66666',
      ownerName: 'Lê Văn Oanh',
      ticketNumber: 'XM008',
      buildingId: buildingList[3]?.id,
      apartmentId: null,
      customerId: null,
      photo: null,
      rentalType: 'tu_lai',
      hasDriver: false,
      pricePerDay: '220000',
      pricePerHour: '35000',
      status: 'available',
      description: 'Xe máy Honda Lead, tiết kiệm xăng, bền bỉ.',
      features: ['Tiết kiệm xăng', 'Bền bỉ'],
      seats: 2,
      fuelType: 'xang',
      transmission: 'tu_dong',
      year: 2022,
      createdBy: host?.id || null,
    },
    {
      type: 'xe_may',
      model: 'SYM Attila ES',
      color: 'Xanh dương',
      plateNumber: '29B1-77777',
      ownerName: 'Phạm Thị Quỳnh',
      ticketNumber: 'XM009',
      buildingId: buildingList[4]?.id,
      apartmentId: null,
      customerId: null,
      photo: null,
      rentalType: null,
      hasDriver: false,
      pricePerDay: null,
      pricePerHour: null,
      status: 'unavailable',
      description: null,
      features: null,
      seats: 2,
      fuelType: 'xang',
      transmission: 'tu_dong',
      year: 2020,
      createdBy: host?.id || null,
    },
    {
      type: 'xe_may',
      model: 'Honda Air Blade',
      color: 'Cam',
      plateNumber: '30A1-88888',
      ownerName: 'Hoàng Văn Sơn',
      ticketNumber: 'XM010',
      buildingId: buildingList[4]?.id,
      apartmentId: null,
      customerId: null,
      photo: null,
      rentalType: 'tu_lai',
      hasDriver: false,
      pricePerDay: '280000',
      pricePerHour: '45000',
      status: 'available',
      description:
        'Xe máy Honda Air Blade 2023, mạnh mẽ, phù hợp mọi địa hình.',
      features: ['Mạnh mẽ', 'Phù hợp mọi địa hình'],
      seats: 2,
      fuelType: 'xang',
      transmission: 'tu_dong',
      year: 2023,
      createdBy: host?.id || null,
    },
  ];

  const vehicles: Vehicle[] = [];

  for (const data of vehiclesData) {
    // Check if vehicle already exists (by plate number)
    const existing = await vehicleRepository.findOne({
      where: { plateNumber: data.plateNumber },
    });

    if (!existing) {
      // Generate slug from model, plateNumber, or type
      const slugBase = data.model || data.plateNumber || `xe-${data.type || 'unknown'}`;
      const slug = await ensureUniqueSlug(vehicleRepository, slugBase);

      const vehicle = vehicleRepository.create({
        ...data,
        slug,
      });
      const saved = await vehicleRepository.save(vehicle);
      vehicles.push(saved);
    } else {
      // Update existing vehicle with slug if missing
      if (!existing.slug) {
        const slugBase = existing.model || existing.plateNumber || `xe-${existing.type || 'unknown'}`;
        existing.slug = await ensureUniqueSlug(vehicleRepository, slugBase, existing.id);
        await vehicleRepository.save(existing);
      }
      vehicles.push(existing);
    }
  }

  console.log(
    `✅ Created ${vehicles.length} vehicles (${vehiclesData.length} total)`,
  );
  return vehicles;
}
